/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PokerGame_GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

import javax.swing.GroupLayout;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.awt.Color;
import java.awt.SystemColor;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.awt.event.ActionEvent;

/**
 *
 * @author kotin
 */
public class LoginPage extends javax.swing.JFrame {

	/**
	 * Creates new form LoginPage
	 */
	public LoginPage() {
		getContentPane().setBackground(new Color(238, 232, 170));
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		username = new javax.swing.JLabel();
		password = new javax.swing.JLabel();
		userText = new javax.swing.JTextField();
		passField = new javax.swing.JPasswordField();
		LoginButton = new javax.swing.JButton();
		CancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setPreferredSize(new java.awt.Dimension(800, 400));

		username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		username.setText("Username:");

		password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		password.setText("Password:");

		userText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		userText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				userTextActionPerformed(evt);
			}
		});

		passField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		passField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				passFieldActionPerformed(evt);
			}
		});

		LoginButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		LoginButton.setText("Login");
		LoginButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				LoginButtonActionPerformed(evt);
			}
		});

		CancelButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		CancelButton.setText("Cancel");
		CancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CancelButtonActionPerformed(evt);
			}
		});

		JButton btnNewButton = new JButton("Guest Mode");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				new PokerDesign("");
				dispose();
			}
		});
		btnNewButton.setFont(new Font("Tahoma", Font.PLAIN, 14));

		JButton btnNewButton_1 = new JButton("or Sign Up");
		btnNewButton_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				new CreateAnAccount();
				dispose();
			}
		});
		btnNewButton_1.setFont(new Font("Tahoma", Font.PLAIN, 14));

		JLabel lblNewLabel = new JLabel("LOGIN TO YOUR WING ACCOUNT");
		lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
		lblNewLabel.setFont(new Font("MS Reference Sans Serif", Font.BOLD, 24));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup().addGap(64)
						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup().addComponent(username).addContainerGap(604,
										Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup().addComponent(password)
										.addPreferredGap(ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
												.addComponent(passField, GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
												.addGroup(layout.createSequentialGroup()
														.addGroup(layout.createParallelGroup(Alignment.LEADING)
																.addComponent(CancelButton).addComponent(btnNewButton))
														.addGap(56)
														.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
																.addComponent(btnNewButton_1, GroupLayout.DEFAULT_SIZE,
																		GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addComponent(LoginButton, GroupLayout.DEFAULT_SIZE,
																		GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
												.addComponent(userText))
										.addGap(83))))
				.addGroup(layout.createSequentialGroup().addContainerGap(210, Short.MAX_VALUE).addComponent(lblNewLabel)
						.addGap(143)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addContainerGap().addComponent(lblNewLabel).addGap(45)
				.addGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(username).addComponent(userText,
						GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(65)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(password).addComponent(passField,
						GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(32)
				.addGroup(layout
						.createParallelGroup(Alignment.BASELINE).addComponent(LoginButton).addComponent(CancelButton))
				.addGap(18)
				.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(btnNewButton_1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(btnNewButton, GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
				.addContainerGap(14, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);
		setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void userTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userTextActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_userTextActionPerformed

	private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_passFieldActionPerformed

	private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LoginButtonActionPerformed
		// TODO add your handling code here:
		String usernameText = userText.getText();
		String passwordText = String.valueOf(passField.getPassword());
		try {
			if(checkForUser(usernameText,passwordText)) {
				new PokerDesign(usernameText);
				dispose();
			}else {
				JOptionPane.showMessageDialog(passField, "Wrong username or password");
			}
		} catch (BiffException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}// GEN-LAST:event_LoginButtonActionPerformed

	private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CancelButtonActionPerformed
		// TODO add your handling code here:
		System.exit(0);
	}// GEN-LAST:event_CancelButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginPage().setVisible(true);
			}
		});
	}

	public boolean checkForUser(String username, String passcode) throws IOException, BiffException {
		if(username.equals("") || passcode.equals("")) {
			return false;
		}
		
		String inputFile = "src\\Player_Record\\record.xls";
		File inputWorkbook = new File(inputFile);
		Workbook w;
		try {
			w = Workbook.getWorkbook(inputWorkbook);

			Sheet sheet = w.getSheet(0);

			Cell[] cols = sheet.getColumn(0);
			for (int i = 0; i < cols.length; i++) {
				if (cols[i].getContents().equals(username)) {
					if(sheet.getColumn(1)[i].getContents().equals(passcode)) {
						return true;
					}
					else {
						return false;
					}
				}

				System.out.println("the usernames is: " + cols[i].getContents());
				System.out.println("the password is: " + sheet.getColumn(1)[i].getContents());
			}
			
			return false;

		} catch (BiffException e) {
			e.printStackTrace();
			return false;
		}
	}
	
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton CancelButton;
	private javax.swing.JButton LoginButton;
	private javax.swing.JPasswordField passField;
	private javax.swing.JLabel password;
	private javax.swing.JTextField userText;
	private javax.swing.JLabel username;
}
